# Generated by Django 5.0.6 on 2024-12-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='theme',
            field=models.CharField(default='math', max_length=100),
            preserve_default=False,
        ),
    ]
